version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - app-network
      
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - 8090:8080
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    links:
      - kafka
      - zookeeper
    networks:
      - app-network

  email-verifier:
    # image: aim41tt/email-verifier:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email-verifier
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_LISTENER_CONCURRENCY: 2
      CONSUMER_GRUP_ID: EmailVerifer
      CONSUMER_TOPIC_NAME: verifer
      GMAIL_USERNAME:  ${GMAIL_USERNAME}
      GMAIL_PASSWORD_APP: ${GMAIL_PASSWORD_APP}
	  #LOG_LEVEL: debug error fatal info off trace warn
	  LOG_LEVEL: warn 
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    links:
      - kafka
    networks:
      - app-network

      
networks:
  app-network:
    driver: bridge
